{"name": "test_login_with_invalid_credentials", "status": "passed", "start": 1699967848776, "stop": 1699967850266, "uuid": "125681f3-f3d0-432c-8e90-8e86ac188501", "historyId": "2628823e04ad24cee2f8a49649004858", "testCaseId": "2628823e04ad24cee2f8a49649004858", "fullName": "tests.test_login.TestLogin#test_login_with_invalid_credentials", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "awaisahmad-latitude-5490"}, {"name": "thread", "value": "130429-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}